# Generated by Django 5.2.7 on 2025-10-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_noticemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
